### PR TITLE
conditional-failure-1

### PR DESCRIPTION
**Pull request by frederikhors**
What do you think about this?

Can we reduce more?

Can we do it more elegantly?

From 28.29 KB to 26.8 KB now.

### CODE REVIEW

**Comment by frederikhors** [comment]
You're right.

I updated.

**Comment by frederikhors** [comment]
28.29 KB > 26.47 KB.

Do you like it?

**Comment by frederikhors** [comment]
But there is a problem now:

```
src/index.js → dist/yrv.js, dist/yrv.es.js...
(!) Plugin svelte: 'IS_PRODUCTION' is not defined
src\Router.svelte
101: {/if}
102:
103: {#if !IS_PRODUCTION && failure && !fallback && !nofallback}
           ^
104:   <fieldset data-failure>
105:     <legend>Router failure: {path}</legend>
src\Route.svelte
104: </script>
105:
106: {#if !IS_PRODUCTION && failure}
           ^
107:   <p data-failure>{failure}</p>
108: {/if}
created dist/yrv.js, dist/yrv.es.js in 3.6s
```

**Comment by pateketrueke** [comment]
Yeah, seems like there's no way to remove dead code from templates... 🤔

**Comment by frederikhors** [comment]
> Yeah, seems like there's no way to remove dead code from templates... 🤔

THE CODE IS GONE! It works! There is only the problem of warning in console!

**Comment by pateketrueke** [comment]
Interesting, there's a way to get rid of the warning or is OK to go ahead?

**Comment by frederikhors** [comment]
As stated here: https://github.com/sveltejs/svelte/issues/4662#issuecomment-612491640 there is apparently no way ther then handle it in Rollup's `onwarn` function.

I'll update it now.

**Comment by frederikhors** [comment]
Updated. No more warning in console.

**Comment by pateketrueke** [comment]
Thank you.

Now, the thing is that final-users won't benefit of the supressed warnings.

We should then bundle two versions so user can pick based on their preference, but that leads to a another question: how to tell svelte-compiler which version pick?

When you consume a svelte component it should point to the `./src/main.js` to make it work properly, how we're going to deal with this IS_PRODUCTION flag under that conditions? 🤔

**Comment by frederikhors** [comment]
Oh dear, here I'm not an expert.

And maybe I don't even understand what you mean.

**Comment by pateketrueke** [comment]
What I mean is that `IS_PRODUCTION` is granted only during build time of `yrv` itself, but what happens if we consume this new version afterwards? We'll need to enabled `IS_PRODUCTION` too in our pipeline?

I'm afraid of releasing something that was not integrated properly, which kind of tests we'll need to ensure the results will work as wee see in CI?

Do you get what I mean?

**Comment by frederikhors** [comment]
I tried. It doesn't work.

It need `IS_PRODUCTION`.

**Comment by frederikhors** [comment]
I'm sad.

**Comment by frederikhors** [comment]
Can you ask, as a mantainer, to the Svelte team about this?

**Comment by pateketrueke** [comment]
If we were able to preprocess the files in `./src` and strip-out code we don't need, then we could have a copy of that sources, e.g. `import { router } from 'yrv/debug';` — and that's clean for final users without require specific config, isn't?

**Pull request closed without merging**
