### PR TITLE
first-reduction

### PR DESCRIPTION
**Pull request by frederikhors**

### CODE REVIEW

**Comment by pateketrueke** [comment]
It would be interesting see the % of reduction of this change. 🤔

**Comment by frederikhors** [comment]
Very small, but why not?

**Comment by pateketrueke** [comment]
I would like it works as follows:


```js
import { Router } from 'yrv';
import queryString from 'query-string';
Router.qs = queryString;
```

By default we should export a mock for `qs` that simply does nothing on `parse()` and `stringify()` to keep the rest of code without changes.

I think we could reduce more if we drop `query-string` from the built-ins as you said. 👍

**Comment by frederikhors** [comment]
> By default we should export a mock for qs that simply does nothing on parse() and stringify() to keep the rest of code without changes.

I do not agree.

Just remove it like `svelte-spa-router` does: https://github.com/ItalyPaleAle/svelte-spa-router#querystring-parameters:

> Querystring parameters
> 
> You can also extract "querystring" parameters from the hash of the page. This isn't the real querystring, as it's located after the # character in the URL, but it can be used in a similar way. For example: #/books?show=authors,titles&order=1.
> 
> When svelte-spa-router finds a "querystring" in the hash, it separates that from the location and returns it as a string in the Svelte store $querystring. For example:
> 
> <script>
> import {location, querystring} from 'svelte-spa-router'
> </script>
> <p>The current page is: {$location}</p>
> <p>The querystring is: {$querystring}</p>
> With the example above, this would print:
> 
> The current page is: /books
> The querystring is: show=authors,titles&order=1
> It's important to note that, to keep this component lightweight, svelte-spa-router does not parse the "querystring". If you want to parse the value of $querystring, you can use third-party modules such as qs in your application.

**Comment by pateketrueke** [comment]
If we remove it, how deal with the current tests that are using it without having to parse/stringify back? 🤔

**Comment by frederikhors** [comment]
You can merge this one because it's safe.

After we can decide what to do with `query-string`.

**Pull request merged**
